name: Build SMAPI Mod (Ubuntu)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      # Build the project
      - name: Restore
        run: dotnet restore MiniPhone/MiniPhone.csproj

      - name: Build
        run: dotnet build MiniPhone/MiniPhone.csproj --configuration Release

      # Upload compiled DLL + assets
      - name: Upload Mod
        uses: actions/upload-artifact@v4
        with:
          name: MiniPhone
          path: MiniPhone/bin/Release/net6.0/
